name: Deploy Azure Function (Linux Consumption)

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install Azure Functions Core Tools
        run: |
          curl -sL https://deb.nodesource.com/setup_18.x | sudo -E bash -
          sudo apt-get install -y nodejs
          sudo npm install -g azure-functions-core-tools@4 --unsafe-perm true

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt

      - name: Deploy to Azure Function App
        run: |
          func azure functionapp publish task8hd-smartbot-func --python
